class PipelineError(Exception): ...


class StageContractError(PipelineError): ...


class MissingPortError(PipelineError): ...


class DagValidationError(PipelineError): ...


class DagDuplicateNodeError(DagValidationError): ...


class DagMissingDependencyError(DagValidationError): ...


class DagCycleError(DagValidationError): ...


class SchedulerError(PipelineError): ...


class SchedulerTimeoutError(SchedulerError): ...


class SchedulerRetryError(SchedulerError): ...
