class PipelineError(Exception): ...


class StageContractError(PipelineError): ...


class MissingPortError(PipelineError): ...


class DAGError(PipelineError): ...


class DAGDuplicateNodeError(DAGError): ...


class DAGMissingDependencyError(DAGError): ...


class DAGCycleError(DAGError): ...


class DAGExecutionError(DAGError): ...


class DAGInputError(DAGExecutionError): ...
