name: "Physics test"
description: "Analytical/asymptote/empirical verification"
title: "[phys-test] <short summary>"
labels: ["type:test","physics"]
body:
  - type: textarea
    id: reference
    attributes:
      label: Reference equation or source
      placeholder: "Treacy/Martinez equation, limit R→∞ ..."
  - type: textarea
    id: protocol
    attributes:
      label: Test protocol
      value: |
        - Inputs: ...
        - Sweep: ...
        - Tolerance: ...
  - type: textarea
    id: artifacts
    attributes:
      label: Expected artifacts
      value: |
        - [ ] Notebook with plots
        - [ ] CSV/Parquet results
        - [ ] Figure(s) for poster
