name: "Task"
description: "Small unit of work (≤2 days), e.g., implement a function/class"
title: "[task] <short summary>"
labels: ["type:task"]
body:
  - type: input
    id: parent
    attributes:
      label: Parent Feature URL
      placeholder: "https://github.com/<org>/<repo>/issues/<id>"
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ] Code + unit tests
        - [ ] Docstring / README snippet (if user-facing)
  - type: dropdown
    id: area
    attributes:
      label: Area
      options: ["phys-pipeline","abcdef-sim","research-utils","cpa-sim","infra/docs"]
  - type: dropdown
    id: size
    attributes:
      label: Size
      options: ["XS","S","M"]
  - type: input
    id: estimate
    attributes:
      label: Estimate (hrs)
      placeholder: "e.g., 4"
